# Generated by Django 5.1.2 on 2025-01-30 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Contact_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, default='', max_length=10, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(default='Found', max_length=10)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('documents', 'Documents'), ('keys', 'Keys'), ('books_stationary', 'Books & Stationary'), ('bags_luggage', 'Bags & Luggage'), ('sporting_goods', 'Sporting Goods'), ('toys_games', 'Toys & Games'), ('money', 'Money')], max_length=50)),
                ('date_found', models.DateField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('location_found', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('found_by', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.school')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_by', models.CharField(help_text='Name of the person claiming', max_length=255)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('required_documents', models.CharField(choices=[('id_card', 'ID Card'), ('birth_certificate', 'Birth Certificate'), ('proof_of_address', 'Proof of Address')], max_length=20)),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='document_uploads/')),
                ('other_document', models.CharField(blank=True, help_text="If 'Other' is selected, specify the document.", max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('contact_number', models.CharField(blank=True, help_text='Your contact number', max_length=15, null=True)),
                ('reason_for_claim', models.TextField(blank=True, help_text='Reason for claiming the item', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks', null=True)),
                ('claim_type', models.CharField(choices=[('Face-to-Face', 'Face-to-Face'), ('Online', 'Online')], help_text='Claim type (e.g. Face-to-Face)', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('found_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli.founditem')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli.school')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClaimProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_by', models.CharField(help_text='Name of the person claiming', max_length=255)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('required_documents', models.CharField(choices=[('id_card', 'ID Card'), ('birth_certificate', 'Birth Certificate'), ('proof_of_address', 'Proof of Address')], max_length=20)),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='document_uploads/')),
                ('other_document', models.CharField(blank=True, help_text="If 'Other' is selected, specify the document.", max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('contact_number', models.CharField(blank=True, help_text='Your contact number', max_length=15, null=True)),
                ('reason_for_claim', models.TextField(blank=True, help_text='Reason for claiming the item', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks', null=True)),
                ('claim_type', models.CharField(choices=[('Face-to-Face', 'Face-to-Face'), ('Online', 'Online')], help_text='Claim type (e.g. Face-to-Face)', max_length=20)),
                ('found_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Appli.founditem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli.school')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('User', 'User'), ('ADMIN', 'Admin')], default='User', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.school')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_by', models.CharField(max_length=255)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('claim_type', models.CharField(choices=[('Face-to-Face', 'Face-to-Face'), ('Online', 'Online')], default='Online', max_length=20)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.founditem')),
                ('claim_procedure', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli.onlineclaimprocedure')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli.school')),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, default='', max_length=10, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(default='Lost', max_length=10)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('documents', 'Documents'), ('keys', 'Keys'), ('books_stationary', 'Books & Stationary'), ('bags_luggage', 'Bags & Luggage'), ('sporting_goods', 'Sporting Goods'), ('toys_games', 'Toys & Games'), ('money', 'Money')], max_length=50)),
                ('date_lost', models.DateField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('location_lost', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('lost_by', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.school')),
            ],
        ),
        migrations.CreateModel(
            name='F2FClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_by', models.CharField(max_length=255)),
                ('claimed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('claim_type', models.CharField(choices=[('Face-to-Face', 'Face-to-Face'), ('Online', 'Online')], default='Online', max_length=20)),
                ('claim_procedure', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli.claimprocedure')),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.founditem')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli.school')),
            ],
        ),
    ]
