# Generated by Django 5.1.2 on 2025-01-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='Contact_number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='Name',
            new_name='name',
        ),
    ]
