# Generated by Django 5.1.2 on 2025-01-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0002_rename_address_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_level',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('Senior High', 'Senior High'), ('College', 'College')], default='High School', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='school_picture',
            field=models.ImageField(blank=True, null=True, upload_to='school_pictures/'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
